version: '3'
services:
    api:
        build:
            context: ./
            dockerfile: .docker/prod/Dockerfile
        image: test-task-loyalty-service
        container_name: loyalty-api
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        ports:
            - "8000:8000"
